### PR TITLE
Make nodes counter red if there were selected more nodes than allowed in-game (91 now)

### PR DESCRIPTION
**Pull request by bivant**
You can test changes here https://bivant.github.io/mwo_skill_planner/
Looks like Tarogato doesn't know about my push request, so I applied patches to the fork from your repository.

### CODE REVIEW

**Comment by pachonk** [comment]
This definitely needs to be squashed.

**Comment by pachonk** [comment]
This is broken currently, I can click on any skill whether I have the skill's parent or not.

**Comment by bivant** [comment]
@pachonk  It's not broken. This is "Free selection" mode, opposite to "Strict selection" (that can be changed in settings at any time). 
Free selection disables rule of "only connected nodes can be selected" for more freedom to play with nodes. It's enabled by default (that can be changed also). I usually start with key nodes and adds others from bottom to top.
"Strict selection" is great then tree is almoust completed but is takes too much time/clicks if you start from scratch.

**Comment by pachonk** [comment]
:+1: Sorry, it wasn't in the PR description and it majorly changed functionality.
Perhaps default could remain the same, and it could be turned off?
All good, just wanted to give it a look over.
There's some misc commented console logs and such that should probably be removed, other than that I didn't look too hard.
Also, there's a lot of commits. It would be nice if they were one commit adding the feature, and you summarize what the feature consists of for the sake of being able to know exactly what every PR's intention is.
No my repo, but it was a big enough changeset that I wanted to code review a bit.

**Comment by bivant** [comment]
Actually this is PR for all the changes I've made from the time I started to tweak the project for my needs.
Every "big" commit is usually a new feature.
I'm not familiar with fork/push request workflow yet. And I know almoust nothing about javascript :)
So my focus was on the changes, not how to structure them for pushing "feature-by-feature".

@nbarnes if you need some explanations or changes in structure of my push request feel free to ask. I was a bit desperate at making my changes available for all, not at my own git-page that I don't what to advertise.

**Comment by nbarnes** [comment]
Nah, s'cool. I just need a weekend to review this before merging. I'm happy to maintain a project rather than just deploy something solo.

**Pull request merged**
